/:
  Controller: "Main"
  Action: "home"

/register:
  Controller: "Security"
  Action: "register"

/login:
  Controller: "Security"
  Action: "login"

/logout:
  Controller: "Security"
  Action: "logout"

/dashboard:
  Controller: "Main"
  Action: "dashboard"
  Security: true
  Role: ["admin", "author"]

/confirm-email:
  Controller: "Security"
  Action: "confirmAccount"

/request-activate-account:
  Controller: "Security"
  Action: "requestActivateAccount"

/activate-account:
  Controller: "Security"
  Action: "activateAccount"

/request-password-reset:
  Controller: "Security"
  Action: "requestPasswordReset"

/reset-password:
  Controller: "Security"
  Action: "resetPassword"

/create-page:
  Controller: "PageController"
  Action: "create"

/store-page:
  Controller: "PageController"
  Action: "store"

/profil-user:
  Controller: "UserController"
  Action: "profil"

/edit-user:
  Controller: "UserController"
  Action: "edit"

/update-profil:
  Controller: "UserController"
  Action: "update"

/list-users:
  Controller: "UserController"
  Action: "list"
