/:
  Controller: "Main"
  Action: "home"

/register:
  Controller: "Security"
  Action: "register"

/login:
  Controller: "Security"
  Action: "login"

/logout:
  Controller: "Security"
  Action: "logout"

/dashboard:
  Controller: "Security"
  Action: "dashboard"
  Security: true
  Role: ["admin", "author"]

/request-password-reset:
  Controller: "Security"
  Action: "requestPasswordReset"

/reset-password:
  Controller: "Security"
  Action: "resetPassword"